#my global config
global:
scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
- job_name: 'node'
 dns_sd_configs:
 - names:
   - 'metrics.fresno.cs158b'
